import type { HallmarkLibraryEntry } from './types';

export const hallmarkLibrary: HallmarkLibraryEntry[] = [
  {
    id: 'genomic',
    slug: 'genomic-instability',
    number: 1,
    title: 'Genomic Instability',
    tagline: 'When DNA repair can no longer keep pace with damage',
    summary: 'Accumulated DNA lesions — from replication errors, radiation, and oxidative hits — overwhelm repair pathways. Unrepaired damage drives mutations, cellular dysfunction, and cancer risk.',
    mechanism: 'PARP enzymes consume NAD+ during repair. With age, repair capacity declines while damage rate stays constant or increases. NRF2 upregulates base-excision repair genes; NAD+ fuels PARP-mediated strand repair.',
    whyItMatters: 'Every cell division risks error. Genomic instability is the substrate for cancer and accelerates all other hallmarks through dysfunctional gene expression.',
    visual: 'dna',
    illustrationV2: 'genomic-instability-v2',
    coverage: 85,
    biomarkers: ['8-OHdG', 'γ-H2AX foci', 'micronuclei frequency'],
    relatedCompoundIds: ['nmn', 'sulforaphane', 'glynac'],
    mdxSlug: 'genomic-instability',
    personalPrompts: ['Note any family cancer history', 'Track oxidative stress markers (8-OHdG if tested)', 'Log sleep quality — repair peaks during deep sleep'],
    interventions: [
      { id: 'g1', name: 'NMN / NAD+ restoration', category: 'compound', evidence: 'A', rank: 1, impact: 9, description: 'Replenishes NAD+ pools consumed by PARP during DNA repair. Human trials show restored NAD+ metabolites.', compoundId: 'nmn', pmid: '30475480', tnicAvailable: true },
      { id: 'g2', name: 'Sulforaphane (NRF2)', category: 'compound', evidence: 'A', rank: 2, impact: 8, description: 'Activates NQO1, GST, and other phase-II enzymes that protect DNA from oxidative adducts.', compoundId: 'sulforaphane', pmid: '18454171', tnicAvailable: true },
      { id: 'g3', name: 'Sleep optimization (7–9h)', category: 'lifestyle', evidence: 'A', rank: 3, impact: 8, description: 'DNA repair enzymes peak during slow-wave sleep. Chronic restriction increases double-strand breaks.', tnicAvailable: false },
      { id: 'g4', name: 'GlyNAC glutathione support', category: 'compound', evidence: 'A', rank: 4, impact: 7, description: 'Restores glutathione — primary defense against oxidative DNA damage.', compoundId: 'glynac', pmid: '34129059', tnicAvailable: true },
      { id: 'g5', name: 'Metformin', category: 'clinical', evidence: 'B', rank: 5, impact: 6, description: 'TAME trial candidate. Reduces DNA damage via AMPK and reduced ROS in preclinical models.', pmid: '26579537', tnicAvailable: false },
    ],
  },
  {
    id: 'telomeres',
    slug: 'telomere-attrition',
    number: 2,
    title: 'Telomere Attrition',
    tagline: 'The molecular clock at chromosome ends',
    summary: 'Telomeres shorten with each cell division. Critically short telomeres trigger senescence or apoptosis, limiting tissue regenerative capacity.',
    mechanism: 'Telomerase extends telomeres in stem cells but is silenced in most somatic tissue. Chronic stress and inflammation accelerate attrition via cortisol and ROS.',
    whyItMatters: 'Telomere length correlates with biological age in population studies. It is a readout of cumulative cellular replicative history.',
    visual: 'telomere',
    illustrationV2: 'telomere-attrition-v2',
    coverage: 45,
    biomarkers: ['Leukocyte telomere length', 'Telomerase activity'],
    relatedCompoundIds: ['nmn'],
    mdxSlug: 'telomere-attrition',
    personalPrompts: ['Record chronic stress periods', 'Note recovery time after illness', 'Compare biological age calculator vs chronological age'],
    interventions: [
      { id: 't1', name: 'Stress reduction / HRV training', category: 'lifestyle', evidence: 'A', rank: 1, impact: 8, description: 'Chronic cortisol accelerates telomere attrition. Meditation and breathwork show measurable telomerase activity increases.', tnicAvailable: false },
      { id: 't2', name: 'NMN / NAD+ support', category: 'compound', evidence: 'B', rank: 2, impact: 6, description: 'NAD+ supports sirtuin-mediated telomere maintenance and PARP balance.', compoundId: 'nmn', tnicAvailable: true },
      { id: 't3', name: 'Exercise (moderate, consistent)', category: 'lifestyle', evidence: 'A', rank: 3, impact: 7, description: 'Aerobic training associated with longer telomeres vs sedentary controls in meta-analyses.', tnicAvailable: false },
      { id: 't4', name: 'Omega-3 (EPA+DHA)', category: 'compound', evidence: 'A', rank: 4, impact: 6, description: 'Omega-3 supplementation associated with preserved telomere length in adults vs placebo (Brain Behav Immun 2012). EPA+DHA reduce cortisol and oxidative drivers of attrition (PMID 22245710).', compoundId: 'omega3', pmid: '22245710', tnicAvailable: true },
      { id: 't5', name: 'TA-65 / telomerase activators', category: 'emerging', evidence: 'C', rank: 5, impact: 4, description: 'Astragalus-derived compounds. Mouse data promising; human evidence limited and costly.', tnicAvailable: false },
    ],
  },
  {
    id: 'epigenetic',
    slug: 'epigenetic-alterations',
    number: 3,
    title: 'Epigenetic Alterations',
    tagline: 'When gene expression drifts from its youthful pattern',
    summary: 'DNA methylation, histone modifications, and chromatin remodeling change with age — the "epigenetic clock" — altering which genes are active without changing the DNA sequence.',
    mechanism: 'TET enzymes and alpha-ketoglutarate drive demethylation. Sirtuins (requiring NAD+) deacetylate histones. Both pathways decline with age.',
    whyItMatters: 'Epigenetic age predicts mortality independent of chronological age. Reversal experiments in mice (Yamanaka factors) prove epigenetic aging is partially reversible.',
    visual: 'epigenetic',
    illustrationV2: 'epigenetic-alterations-v2',
    coverage: 78,
    biomarkers: ['Horvath / GrimAge clock', 'DNA methylation panels'],
    relatedCompoundIds: ['cakg', 'nmn', 'resveratrol'],
    mdxSlug: 'epigenetic-alterations',
    personalPrompts: ['Log biological age from Defense Calculator', 'Track diet quality (methyl donors: B12, folate, choline)', 'Note energy consistency week-over-week'],
    interventions: [
      { id: 'e1', name: 'Ca-AKG', category: 'compound', evidence: 'A', rank: 1, impact: 8, description: 'AKG is a cofactor for TET dioxygenases that regulate DNA demethylation. Mouse lifespan extension data.', compoundId: 'cakg', pmid: '33027664', tnicAvailable: true },
      { id: 'e2', name: 'NMN → SIRT1 epigenetic control', category: 'compound', evidence: 'A', rank: 2, impact: 8, description: 'NAD+-dependent sirtuins regulate histone acetylation and heterochromatin stability.', compoundId: 'nmn', tnicAvailable: true },
      { id: 'e3', name: 'Resveratrol → SIRT1 activation', category: 'compound', evidence: 'B', rank: 3, impact: 7, description: 'Phytoalexin that activates SIRT1; synergistic with NAD+ precursors for epigenetic remodeling.', compoundId: 'resveratrol', pmid: '17909917', tnicAvailable: true },
      { id: 'e4', name: 'Caloric moderation / fasting', category: 'lifestyle', evidence: 'A', rank: 4, impact: 7, description: 'Fasting resets methylation patterns in animal models and reduces epigenetic age in pilot human studies.', tnicAvailable: false },
      { id: 'e5', name: 'Epigenetic clock testing', category: 'clinical', evidence: 'B', rank: 5, impact: 5, description: 'GrimAge, DunedinPACE, or TruAge panels to track intervention response over 6–12 months.', tnicAvailable: false },
    ],
  },
  {
    id: 'proteostasis',
    slug: 'loss-of-proteostasis',
    number: 4,
    title: 'Loss of Proteostasis',
    tagline: 'When damaged proteins accumulate faster than cleanup',
    summary: 'The proteostasis network — chaperones, ubiquitin-proteasome, autophagy — fails to clear misfolded proteins, leading to aggregates linked to neurodegeneration.',
    mechanism: 'Glutathione maintains cysteine residues and chaperone function. Oxidized proteins cannot refold. NRF2 upregulates proteasome subunits.',
    whyItMatters: 'Protein aggregation is central to Alzheimer\'s, Parkinson\'s, and ALS. Maintaining proteostasis is foundational to cognitive longevity.',
    visual: 'protein',
    illustrationV2: 'loss-of-proteostasis-v2',
    coverage: 82,
    biomarkers: ['Protein carbonylation', 'GSH/GSSG ratio', 'Ubiquitin conjugates'],
    relatedCompoundIds: ['glynac', 'rala', 'sulforaphane'],
    mdxSlug: 'loss-of-proteostasis',
    personalPrompts: ['Track mental clarity / brain fog', 'Log glutathione index if available', 'Note heat/cold exposure practices'],
    interventions: [
      { id: 'p1', name: 'GlyNAC (glutathione restoration)', category: 'compound', evidence: 'A', rank: 1, impact: 9, description: 'Human trials restore glutathione, reduce oxidative protein damage, improve mitochondrial function.', compoundId: 'glynac', pmid: '36656670', tnicAvailable: true },
      { id: 'p2', name: 'R-Alpha Lipoic Acid', category: 'compound', evidence: 'B', rank: 2, impact: 7, description: 'Regenerates glutathione and vitamin C/E; supports mitochondrial proteostasis.', compoundId: 'rala', tnicAvailable: true },
      { id: 'p3', name: 'Sulforaphane (proteasome upregulation)', category: 'compound', evidence: 'A', rank: 3, impact: 7, description: 'NRF2 activation increases proteasome activity and heat shock protein expression.', compoundId: 'sulforaphane', tnicAvailable: true },
      { id: 'p4', name: 'Sauna / heat shock exposure', category: 'lifestyle', evidence: 'B', rank: 4, impact: 6, description: 'Heat shock proteins refold damaged proteins. Finnish sauna studies link frequency to reduced mortality.', tnicAvailable: false },
      { id: 'p5', name: 'Time-restricted eating', category: 'lifestyle', evidence: 'B', rank: 5, impact: 6, description: 'Fasting windows activate autophagy-proteostasis crosstalk via AMPK/mTOR.', tnicAvailable: false },
    ],
  },
  {
    id: 'mito',
    slug: 'mitochondrial-dysfunction',
    number: 6,
    title: 'Mitochondrial Dysfunction',
    tagline: 'The energy crisis that drives aging',
    summary: 'Mitochondria produce ATP and ROS. With age, biogenesis slows, membrane potential drops, and dysfunctional mitochondria accumulate — reducing energy and increasing oxidative damage.',
    mechanism: 'NAD+ is the rate-limiting cofactor for sirtuins and PARP. AKG fuels the TCA cycle. Resveratrol promotes mitophagy. R-ALA supports complex enzymes.',
    whyItMatters: 'Every high-energy tissue — brain, heart, muscle — depends on mitochondrial output. Mito decline is arguably the most actionable hallmark.',
    visual: 'mito',
    illustrationV2: 'mitochondrial-dysfunction-v2',
    coverage: 95,
    biomarkers: ['NAD+ metabolites', 'Lactate/pyruvate ratio', 'VO2 max', 'Resting metabolic rate'],
    relatedCompoundIds: ['nmn', 'cakg', 'resveratrol', 'rala', 'taurine'],
    mdxSlug: 'mitochondrial-dysfunction',
    personalPrompts: ['Log subjective energy 1–10 daily', 'Track resting heart rate trend', 'Note NAD+ panel results if tested'],
    interventions: [
      { id: 'm1', name: 'NMN / NAD+ precursors', category: 'compound', evidence: 'A', rank: 1, impact: 10, description: 'Restores NAD+ declined ~50% by age 60. Human trials show improved muscle insulin sensitivity and aerobic capacity.', compoundId: 'nmn', pmid: '30475480', tnicAvailable: true },
      { id: 'm2', name: 'Ca-AKG (TCA cycle)', category: 'compound', evidence: 'A', rank: 2, impact: 8, description: 'Fuels mitochondrial respiration and collagen synthesis. 12–14% median lifespan extension in mice.', compoundId: 'cakg', pmid: '33027664', tnicAvailable: true },
      { id: 'm3', name: 'Zone 2 aerobic training', category: 'lifestyle', evidence: 'A', rank: 3, impact: 9, description: 'The single strongest lifestyle intervention for mitochondrial biogenesis via PGC-1α.', tnicAvailable: false },
      { id: 'm4', name: 'Resveratrol (mitophagy)', category: 'compound', evidence: 'B', rank: 4, impact: 7, description: 'Promotes clearance of damaged mitochondria via SIRT1/PINK1 pathway.', compoundId: 'resveratrol', tnicAvailable: true },
      { id: 'm5', name: 'R-Alpha Lipoic Acid', category: 'compound', evidence: 'B', rank: 5, impact: 7, description: 'Cofactor for pyruvate dehydrogenase and complex enzymes; recycles antioxidants in the mitochondrial matrix.', compoundId: 'rala', tnicAvailable: true },
      { id: 'm6', name: 'Taurine', category: 'compound', evidence: 'B', rank: 6, impact: 6, description: 'Age-depleted osmolyte; Singh 2023 Science links deficiency to hallmarks and extends lifespan in animal models.', compoundId: 'taurine', pmid: '37289866', tnicAvailable: true },
      { id: 'm7', name: 'CoQ10 (Ubiquinol)', category: 'compound', evidence: 'B', rank: 7, impact: 7, description: 'Essential electron carrier in Complex I–III of the electron transport chain. Declines ~50% by age 60; ubiquinol form achieves 3× higher plasma levels. Meta-analysis of 17 RCTs confirms reduced hs-CRP and IL-6 (PMID 26267690).', compoundId: 'coq10', pmid: '26267690', tnicAvailable: true },
      { id: 'm8', name: 'Urolithin A (mitophagy)', category: 'compound', evidence: 'A', rank: 8, impact: 8, description: 'Phase 2 RCT confirmed urolithin A activates mitophagy and improves aerobic capacity and muscle strength in adults ≥65 vs placebo (PMID 35391504).', compoundId: 'urolithina', pmid: '35391504', tnicAvailable: true },
    ],
  },
];