import type { HallmarkLibraryEntry } from './types';

export const hallmarkLibrary: HallmarkLibraryEntry[] = [
  {
    id: 'genomic',
    slug: 'genomic-instability',
    number: 1,
    title: 'Genomic Instability',
    tagline: 'When DNA repair can no longer keep pace with damage',
    summary: 'Accumulated DNA lesions — from replication errors, radiation, and oxidative hits — overwhelm repair pathways. Unrepaired damage drives mutations, cellular dysfunction, and cancer risk.',
    mechanism: 'PARP enzymes consume NAD+ during repair. With age, repair capacity declines while damage rate stays constant or increases. NRF2 upregulates base-excision repair genes; NAD+ fuels PARP-mediated strand repair.',
    whyItMatters: 'Every cell division risks error. Genomic instability is the substrate for cancer and accelerates all other hallmarks through dysfunctional gene expression.',
    visual: 'dna',
    coverage: 85,
    biomarkers: ['8-OHdG', 'γ-H2AX foci', 'micronuclei frequency'],
    relatedCompoundIds: ['nmn', 'sulforaphane', 'glynac'],
    mdxSlug: 'genomic-instability',
    personalPrompts: ['Note any family cancer history', 'Track oxidative stress markers (8-OHdG if tested)', 'Log sleep quality — repair peaks during deep sleep'],
    interventions: [
      { id: 'g1', name: 'NMN / NAD+ restoration', category: 'compound', evidence: 'A', rank: 1, impact: 9, description: 'Replenishes NAD+ pools consumed by PARP during DNA repair. Human trials show restored NAD+ metabolites.', compoundId: 'nmn', pmid: '30475480', tnicAvailable: true },
      { id: 'g2', name: 'Sulforaphane (NRF2)', category: 'compound', evidence: 'A', rank: 2, impact: 8, description: 'Activates NQO1, GST, and other phase-II enzymes that protect DNA from oxidative adducts.', compoundId: 'sulforaphane', pmid: '18454171', tnicAvailable: true },
      { id: 'g3', name: 'Sleep optimization (7–9h)', category: 'lifestyle', evidence: 'A', rank: 3, impact: 8, description: 'DNA repair enzymes peak during slow-wave sleep. Chronic restriction increases double-strand breaks.', tnicAvailable: false },
      { id: 'g4', name: 'GlyNAC glutathione support', category: 'compound', evidence: 'A', rank: 4, impact: 7, description: 'Restores glutathione — primary defense against oxidative DNA damage.', compoundId: 'glynac', pmid: '34129059', tnicAvailable: true },
      { id: 'g5', name: 'Metformin', category: 'clinical', evidence: 'B', rank: 5, impact: 6, description: 'TAME trial candidate. Reduces DNA damage via AMPK and reduced ROS in preclinical models.', pmid: '26579537', tnicAvailable: false },
    ],
  },
  {
    id: 'telomeres',
    slug: 'telomere-attrition',
    number: 2,
    title: 'Telomere Attrition',
    tagline: 'The molecular clock at chromosome ends',
    summary: 'Telomeres shorten with each cell division. Critically short telomeres trigger senescence or apoptosis, limiting tissue regenerative capacity.',
    mechanism: 'Telomerase extends telomeres in stem cells but is silenced in most somatic tissue. Chronic stress and inflammation accelerate attrition via cortisol and ROS.',
    whyItMatters: 'Telomere length correlates with biological age in population studies. It is a readout of cumulative cellular replicative history.',
    visual: 'telomere',
    coverage: 45,
    biomarkers: ['Leukocyte telomere length', 'Telomerase activity'],
    relatedCompoundIds: ['nmn'],
    mdxSlug: 'telomere-attrition',
    personalPrompts: ['Record chronic stress periods', 'Note recovery time after illness', 'Compare biological age calculator vs chronological age'],
    interventions: [
      { id: 't1', name: 'Stress reduction / HRV training', category: 'lifestyle', evidence: 'A', rank: 1, impact: 8, description: 'Chronic cortisol accelerates telomere attrition. Meditation and breathwork show measurable telomerase activity increases.', tnicAvailable: false },
      { id: 't2', name: 'NMN / NAD+ support', category: 'compound', evidence: 'B', rank: 2, impact: 6, description: 'NAD+ supports sirtuin-mediated telomere maintenance and PARP balance.', compoundId: 'nmn', tnicAvailable: true },
      { id: 't3', name: 'Exercise (moderate, consistent)', category: 'lifestyle', evidence: 'A', rank: 3, impact: 7, description: 'Aerobic training associated with longer telomeres vs sedentary controls in meta-analyses.', tnicAvailable: false },
      { id: 't4', name: 'Omega-3 (EPA+DHA)', category: 'compound', evidence: 'A', rank: 4, impact: 6, description: 'Omega-3 supplementation associated with preserved telomere length in adults vs placebo (Brain Behav Immun 2012). EPA+DHA reduce cortisol and oxidative drivers of attrition (PMID 22245710).', compoundId: 'omega3', pmid: '22245710', tnicAvailable: true },
      { id: 't5', name: 'TA-65 / telomerase activators', category: 'emerging', evidence: 'C', rank: 5, impact: 4, description: 'Astragalus-derived compounds. Mouse data promising; human evidence limited and costly.', tnicAvailable: false },
    ],
  },
  {
    id: 'epigenetic',
    slug: 'epigenetic-alterations',
    number: 3,
    title: 'Epigenetic Alterations',
    tagline: 'When gene expression drifts from its youthful pattern',
    summary: 'DNA methylation, histone modifications, and chromatin remodeling change with age — the "epigenetic clock" — altering which genes are active without changing the DNA sequence.',
    mechanism: 'TET enzymes and alpha-ketoglutarate drive demethylation. Sirtuins (requiring NAD+) deacetylate histones. Both pathways decline with age.',
    whyItMatters: 'Epigenetic age predicts mortality independent of chronological age. Reversal experiments in mice (Yamanaka factors) prove epigenetic aging is partially reversible.',
    visual: 'epigenetic',
    coverage: 78,
    biomarkers: ['Horvath / GrimAge clock', 'DNA methylation panels'],
    relatedCompoundIds: ['cakg', 'nmn', 'resveratrol'],
    mdxSlug: 'epigenetic-alterations',
    personalPrompts: ['Log biological age from Defense Calculator', 'Track diet quality (methyl donors: B12, folate, choline)', 'Note energy consistency week-over-week'],
    interventions: [
      { id: 'e1', name: 'Ca-AKG', category: 'compound', evidence: 'A', rank: 1, impact: 8, description: 'AKG is a cofactor for TET dioxygenases that regulate DNA demethylation. Mouse lifespan extension data.', compoundId: 'cakg', pmid: '33027664', tnicAvailable: true },
      { id: 'e2', name: 'NMN → SIRT1 epigenetic control', category: 'compound', evidence: 'A', rank: 2, impact: 8, description: 'NAD+-dependent sirtuins regulate histone acetylation and heterochromatin stability.', compoundId: 'nmn', tnicAvailable: true },
      { id: 'e3', name: 'Resveratrol → SIRT1 activation', category: 'compound', evidence: 'B', rank: 3, impact: 7, description: 'Phytoalexin that activates SIRT1; synergistic with NAD+ precursors for epigenetic remodeling.', compoundId: 'resveratrol', pmid: '17909917', tnicAvailable: true },
      { id: 'e4', name: 'Caloric moderation / fasting', category: 'lifestyle', evidence: 'A', rank: 4, impact: 7, description: 'Fasting resets methylation patterns in animal models and reduces epigenetic age in pilot human studies.', tnicAvailable: false },
      { id: 'e5', name: 'Epigenetic clock testing', category: 'clinical', evidence: 'B', rank: 5, impact: 5, description: 'GrimAge, DunedinPACE, or TruAge panels to track intervention response over 6–12 months.', tnicAvailable: false },
    ],
  },
  {
    id: 'proteostasis',
    slug: 'loss-of-proteostasis',
    number: 4,
    title: 'Loss of Proteostasis',
    tagline: 'When damaged proteins accumulate faster than cleanup',
    summary: 'The proteostasis network — chaperones, ubiquitin-proteasome, autophagy — fails to clear misfolded proteins, leading to aggregates linked to neurodegeneration.',
    mechanism: 'Glutathione maintains cysteine residues and chaperone function. Oxidized proteins cannot refold. NRF2 upregulates proteasome subunits.',
    whyItMatters: 'Protein aggregation is central to Alzheimer\'s, Parkinson\'s, and ALS. Maintaining proteostasis is foundational to cognitive longevity.',
    visual: 'protein',
    coverage: 82,
    biomarkers: ['Protein carbonylation', 'GSH/GSSG ratio', 'Ubiquitin conjugates'],
    relatedCompoundIds: ['glynac', 'rala', 'sulforaphane'],
    mdxSlug: 'loss-of-proteostasis',
    personalPrompts: ['Track mental clarity / brain fog', 'Log glutathione index if available', 'Note heat/cold exposure practices'],
    interventions: [
      { id: 'p1', name: 'GlyNAC (glutathione restoration)', category: 'compound', evidence: 'A', rank: 1, impact: 9, description: 'Human trials restore glutathione, reduce oxidative protein damage, improve mitochondrial function.', compoundId: 'glynac', pmid: '36656670', tnicAvailable: true },
      { id: 'p2', name: 'R-Alpha Lipoic Acid', category: 'compound', evidence: 'B', rank: 2, impact: 7, description: 'Regenerates glutathione and vitamin C/E; supports mitochondrial proteostasis.', compoundId: 'rala', tnicAvailable: true },
      { id: 'p3', name: 'Sulforaphane (proteasome upregulation)', category: 'compound', evidence: 'A', rank: 3, impact: 7, description: 'NRF2 activation increases proteasome activity and heat shock protein expression.', compoundId: 'sulforaphane', tnicAvailable: true },
      { id: 'p4', name: 'Sauna / heat shock exposure', category: 'lifestyle', evidence: 'B', rank: 4, impact: 6, description: 'Heat shock proteins refold damaged proteins. Finnish sauna studies link frequency to reduced mortality.', tnicAvailable: false },
      { id: 'p5', name: 'Time-restricted eating', category: 'lifestyle', evidence: 'B', rank: 5, impact: 6, description: 'Fasting windows activate autophagy-proteostasis crosstalk via AMPK/mTOR.', tnicAvailable: false },
    ],
  },
  {
    id: 'autophagy',
    slug: 'disabled-autophagy',
    number: 5,
    title: 'Disabled Autophagy',
    tagline: 'Cellular recycling slows — junk accumulates',
    summary: 'Autophagy ("self-eating") clears damaged organelles and proteins. mTOR overactivation and NAD+ decline suppress this cleanup with age.',
    mechanism: 'AMPK activates autophagy; mTOR suppresses it. SIRT1 deacetylates autophagy regulators. NAD+ decline reduces SIRT1 activity.',
    whyItMatters: 'Autophagy is the intersection of proteostasis, mitochondrial health, and nutrient sensing. Without it, cells accumulate toxic debris.',
    visual: 'autophagy',
    coverage: 70,
    biomarkers: ['LC3-II/LC3-I ratio (research)', 'p62 levels', 'Fasting glucose / ketones'],
    relatedCompoundIds: ['nmn', 'sulforaphane', 'resveratrol', 'spermidine'],
    mdxSlug: 'disabled-autophagy',
    personalPrompts: ['Log fasting window length', 'Track post-meal energy crashes', 'Note exercise intensity and recovery'],
    interventions: [
      { id: 'a1', name: 'Time-restricted eating (16:8+)', category: 'lifestyle', evidence: 'A', rank: 1, impact: 8, description: 'The most accessible autophagy trigger. mTOR suppression during fasting windows activates cleanup.', tnicAvailable: false },
      { id: 'a2', name: 'NMN → SIRT1 autophagy axis', category: 'compound', evidence: 'B', rank: 2, impact: 7, description: 'NAD+-SIRT1 pathway deacetylates ATG proteins, promoting autophagosome formation.', compoundId: 'nmn', tnicAvailable: true },
      { id: 'a3', name: 'Resveratrol → AMPK activation', category: 'compound', evidence: 'B', rank: 3, impact: 7, description: 'AMPK phosphorylation triggers autophagy independent of mTOR.', compoundId: 'resveratrol', tnicAvailable: true },
      { id: 'a4', name: 'Sulforaphane', category: 'compound', evidence: 'B', rank: 4, impact: 6, description: 'NRF2-mediated upregulation of autophagy-related genes in preclinical models.', compoundId: 'sulforaphane', tnicAvailable: true },
      { id: 'a5', name: 'Spermidine', category: 'compound', evidence: 'B', rank: 5, impact: 6, description: 'Induces autophagy via EP300 inhibition. Madeo 2021 memory RCT; dietary epidemiology links intake to longevity.', compoundId: 'spermidine', pmid: '33932338', tnicAvailable: true },
      { id: 'a6', name: 'Urolithin A (Mitopure)', category: 'compound', evidence: 'A', rank: 6, impact: 8, description: 'Activates mitophagy (selective mitochondria autophagy) in human skeletal muscle — Phase 2 RCT confirmed improved muscle mitochondrial gene expression and endurance in older adults (PMID 35391504).', compoundId: 'urolithina', pmid: '35391504', tnicAvailable: true },
    ],
  },
  {
    id: 'mito',
    slug: 'mitochondrial-dysfunction',
    number: 6,
    title: 'Mitochondrial Dysfunction',
    tagline: 'The energy crisis that drives aging',
    summary: 'Mitochondria produce ATP and ROS. With age, biogenesis slows, membrane potential drops, and dysfunctional mitochondria accumulate — reducing energy and increasing oxidative damage.',
    mechanism: 'NAD+ is the rate-limiting cofactor for sirtuins and PARP. AKG fuels the TCA cycle. Resveratrol promotes mitophagy. R-ALA supports complex enzymes.',
    whyItMatters: 'Every high-energy tissue — brain, heart, muscle — depends on mitochondrial output. Mito decline is arguably the most actionable hallmark.',
    visual: 'mito',
    coverage: 95,
    biomarkers: ['NAD+ metabolites', 'Lactate/pyruvate ratio', 'VO2 max', 'Resting metabolic rate'],
    relatedCompoundIds: ['nmn', 'cakg', 'resveratrol', 'rala', 'taurine'],
    mdxSlug: 'mitochondrial-dysfunction',
    personalPrompts: ['Log subjective energy 1–10 daily', 'Track resting heart rate trend', 'Note NAD+ panel results if tested'],
    interventions: [
      { id: 'm1', name: 'NMN / NAD+ precursors', category: 'compound', evidence: 'A', rank: 1, impact: 10, description: 'Restores NAD+ declined ~50% by age 60. Human trials show improved muscle insulin sensitivity and aerobic capacity.', compoundId: 'nmn', pmid: '30475480', tnicAvailable: true },
      { id: 'm2', name: 'Ca-AKG (TCA cycle)', category: 'compound', evidence: 'A', rank: 2, impact: 8, description: 'Fuels mitochondrial respiration and collagen synthesis. 12–14% median lifespan extension in mice.', compoundId: 'cakg', pmid: '33027664', tnicAvailable: true },
      { id: 'm3', name: 'Zone 2 aerobic training', category: 'lifestyle', evidence: 'A', rank: 3, impact: 9, description: 'The single strongest lifestyle intervention for mitochondrial biogenesis via PGC-1α.', tnicAvailable: false },
      { id: 'm4', name: 'Resveratrol (mitophagy)', category: 'compound', evidence: 'B', rank: 4, impact: 7, description: 'Promotes clearance of damaged mitochondria via SIRT1/PINK1 pathway.', compoundId: 'resveratrol', tnicAvailable: true },
      { id: 'm5', name: 'R-Alpha Lipoic Acid', category: 'compound', evidence: 'B', rank: 5, impact: 7, description: 'Cofactor for pyruvate dehydrogenase and complex enzymes; recycles antioxidants in the mitochondrial matrix.', compoundId: 'rala', tnicAvailable: true },
      { id: 'm6', name: 'Taurine', category: 'compound', evidence: 'B', rank: 6, impact: 6, description: 'Age-depleted osmolyte; Singh 2023 Science links deficiency to hallmarks and extends lifespan in animal models.', compoundId: 'taurine', pmid: '37289866', tnicAvailable: true },
      { id: 'm7', name: 'CoQ10 (Ubiquinol)', category: 'compound', evidence: 'B', rank: 7, impact: 7, description: 'Essential electron carrier in Complex I–III of the electron transport chain. Declines ~50% by age 60; ubiquinol form achieves 3× higher plasma levels. Meta-analysis of 17 RCTs confirms reduced hs-CRP and IL-6 (PMID 26267690).', compoundId: 'coq10', pmid: '26267690', tnicAvailable: true },
      { id: 'm8', name: 'Urolithin A (mitophagy)', category: 'compound', evidence: 'A', rank: 8, impact: 8, description: 'Phase 2 RCT confirmed urolithin A activates mitophagy and improves aerobic capacity and muscle strength in adults ≥65 vs placebo (PMID 35391504).', compoundId: 'urolithina', pmid: '35391504', tnicAvailable: true },
    ],
  },
  {
    id: 'senescence',
    slug: 'cellular-senescence',
    number: 7,
    title: 'Cellular Senescence',
    tagline: 'Zombie cells that poison their neighbors',
    summary: 'Senescent cells stop dividing but resist apoptosis, secreting SASP factors (IL-6, MMPs) that drive inflammation and tissue dysfunction.',
    mechanism: 'Telomere crisis, oncogene activation, and DNA damage trigger senescence. SASP spreads dysfunction to neighboring healthy cells.',
    whyItMatters: 'Senolytics (clearing senescent cells) extend healthspan in mice. SASP is a major driver of inflammaging.',
    visual: 'senescence',
    coverage: 75,
    biomarkers: ['p16INK4a expression', 'SASP cytokine panel', 'Senescence-associated β-gal'],
    relatedCompoundIds: ['nmn', 'resveratrol'],
    mdxSlug: 'cellular-senescence',
    personalPrompts: ['Track hs-CRP as SASP proxy', 'Note joint stiffness / slow healing', 'Log inflammation after poor sleep'],
    interventions: [
      { id: 's1', name: 'Fisetin (senolytic)', category: 'emerging', evidence: 'B', rank: 1, impact: 7, description: 'Mayo Clinic trials underway. Flavonoid selectively clears senescent cells in mouse models.', pmid: '30279143', tnicAvailable: false },
      { id: 's2', name: 'NMN (senescence prevention)', category: 'compound', evidence: 'B', rank: 2, impact: 6, description: 'NAD+ restoration delays senescence entry in cell culture via sirtuin-mediated genome stability.', compoundId: 'nmn', tnicAvailable: true },
      { id: 's3', name: 'Resveratrol (SASP modulation)', category: 'compound', evidence: 'B', rank: 3, impact: 6, description: 'Reduces NF-κB-driven SASP secretion in preclinical senescence models.', compoundId: 'resveratrol', tnicAvailable: true },
      { id: 's4', name: 'Exercise', category: 'lifestyle', evidence: 'A', rank: 4, impact: 7, description: 'Clears senescent cells via immune surveillance and reduces SASP in adipose tissue.', tnicAvailable: false },
      { id: 's5', name: 'Dasatinib + Quercetin protocol', category: 'clinical', evidence: 'B', rank: 5, impact: 7, description: 'Physician-supervised senolytic combo. Human pilot data in IPF and diabetic kidney disease.', pmid: '30616957', tnicAvailable: false },
      { id: 's6', name: 'Fisetin (senolytic flavonoid)', category: 'compound', evidence: 'B', rank: 6, impact: 7, description: 'Mayo Clinic pilot RCT showed pulse-dose fisetin (20mg/kg × 2 days/month) significantly reduced p16INK4A and p21 senescence markers and improved physical function in older adults (PMID 31760212). Multiple Phase 2 trials active.', compoundId: 'fisetin', pmid: '31760212', tnicAvailable: true },
    ],
  },
  {
    id: 'stem',
    slug: 'stem-cell-exhaustion',
    number: 8,
    title: 'Stem Cell Exhaustion',
    tagline: 'Regenerative capacity runs dry',
    summary: 'Tissue-specific stem cell pools decline in number and function, impairing repair of muscle, skin, blood, and gut lining.',
    mechanism: 'NAD+ and AKG support stem cell niche signaling. Inflammation and senescence in the niche suppress stem cell activation.',
    whyItMatters: 'Without stem cell renewal, wounds heal slower, muscle wastes, and immune repertoire narrows.',
    visual: 'stem',
    coverage: 68,
    biomarkers: ['CD34+ cell count', 'Wound healing time', 'Muscle recovery rate'],
    relatedCompoundIds: ['cakg', 'nmn'],
    mdxSlug: 'stem-cell-exhaustion',
    personalPrompts: ['Track workout recovery days needed', 'Note skin healing after cuts', 'Log illness recovery duration'],
    interventions: [
      { id: 'st1', name: 'Ca-AKG (stem niche support)', category: 'compound', evidence: 'A', rank: 1, impact: 7, description: 'Supports collagen synthesis and stem cell quiescence in bone marrow niches.', compoundId: 'cakg', tnicAvailable: true },
      { id: 'st2', name: 'NMN (NAD+ stem maintenance)', category: 'compound', evidence: 'B', rank: 2, impact: 7, description: 'NAD+ required for stem cell self-renewal and differentiation in hematopoietic models.', compoundId: 'nmn', tnicAvailable: true },
      { id: 'st3', name: 'Resistance training', category: 'lifestyle', evidence: 'A', rank: 3, impact: 8, description: 'Satellite cell activation in muscle is the best-studied stem cell stimulus in humans.', tnicAvailable: false },
      { id: 'st4', name: 'Reduce chronic inflammation', category: 'lifestyle', evidence: 'A', rank: 4, impact: 7, description: 'Inflammaging suppresses stem cell niches. NRF2 stack targets upstream SASP drivers.', tnicAvailable: false },
      { id: 'st5', name: 'Young plasma / exosome therapies', category: 'emerging', evidence: 'C', rank: 5, impact: 4, description: 'Parabiosis research intriguing but not clinically available for consumers.', tnicAvailable: false },
    ],
  },
  {
    id: 'communication',
    slug: 'altered-intercellular-communication',
    number: 9,
    title: 'Altered Intercellular Communication',
    tagline: 'When cells stop talking correctly',
    summary: 'Hormonal, neuronal, and immune signaling networks become dysregulated. SASP from senescent cells hijacks normal paracrine signaling.',
    mechanism: 'Neuroendocrine decline (GH, sex hormones), insulin resistance, and inflammatory cytokines disrupt tissue coordination.',
    whyItMatters: 'Poor intercellular communication amplifies every other hallmark — inflammation spreads, hormones desync, immunity misfires.',
    visual: 'signaling',
    coverage: 55,
    biomarkers: ['IL-6', 'TNF-α', 'Insulin / HOMA-IR', 'Cortisol rhythm'],
    relatedCompoundIds: ['resveratrol', 'sulforaphane', 'glynac'],
    mdxSlug: 'altered-intercellular-communication',
    personalPrompts: ['Track mood and social energy', 'Log blood sugar patterns', 'Note hormone panel dates'],
    interventions: [
      { id: 'c1', name: 'Anti-inflammatory stack (NRF2)', category: 'compound', evidence: 'A', rank: 1, impact: 7, description: 'Sulforaphane + GlyNAC reduce SASP-driven signaling disruption at the source.', compoundId: 'sulforaphane', tnicAvailable: true },
      { id: 'c2', name: 'Resveratrol (NF-κB modulation)', category: 'compound', evidence: 'B', rank: 2, impact: 6, description: 'Inhibits inflammatory transcription factors that amplify intercellular damage signals.', compoundId: 'resveratrol', tnicAvailable: true },
      { id: 'c3', name: 'Sleep / circadian alignment', category: 'lifestyle', evidence: 'A', rank: 3, impact: 8, description: 'Melatonin, cortisol, and GH pulses coordinate tissue repair. Misalignment disrupts all signaling.', tnicAvailable: false },
      { id: 'c4', name: 'Insulin sensitivity optimization', category: 'lifestyle', evidence: 'A', rank: 4, impact: 8, description: 'Metabolic health is the master regulator of intercellular hormone signaling.', tnicAvailable: false },
      { id: 'c5', name: 'Fisetin (senolytic, SASP removal)', category: 'compound', evidence: 'B', rank: 5, impact: 7, description: 'Removing SASP-secreting senescent cells restores normal paracrine signaling. Fisetin Mayo pilot (PMID 31760212) confirmed reduced p16/p21 burden and improved function — the most accessible consumer senolytic option.', compoundId: 'fisetin', pmid: '31760212', tnicAvailable: true },
      { id: 'c6', name: 'Omega-3 SPM axis (cytokine resolution)', category: 'compound', evidence: 'A', rank: 6, impact: 7, description: 'EPA/DHA-derived resolvins and protectins actively resolve SASP-like cytokine cascades — not just suppressors but active resolution mediators. REDUCE-IT confirmed systemic signaling benefits (PMID 30145934).', compoundId: 'omega3', pmid: '30145934', tnicAvailable: true },
    ],
  },
  {
    id: 'inflammation',
    slug: 'chronic-inflammation',
    number: 10,
    title: 'Chronic Inflammation',
    tagline: 'Inflammaging — the silent accelerator',
    summary: 'Low-grade systemic inflammation increases with age (inflammaging), driven by SASP, gut permeability, and immune senescence. Measured clinically by hs-CRP.',
    mechanism: 'NF-κB is the master inflammatory switch. NRF2 and Nrf2-target genes counterbalance it. Glutathione depletion amplifies ROS-driven inflammation.',
    whyItMatters: 'hs-CRP predicts cardiovascular events and all-cause mortality. Reducing inflammaging has the broadest cross-hallmark impact.',
    visual: 'inflammation',
    coverage: 88,
    biomarkers: ['hs-CRP', 'IL-6', 'Homocysteine', 'Fibrinogen'],
    relatedCompoundIds: ['sulforaphane', 'glynac', 'resveratrol'],
    mdxSlug: 'chronic-inflammation',
    personalPrompts: ['Log hs-CRP in Lab Tracker', 'Track post-meal bloating', 'Note joint pain patterns'],
    interventions: [
      { id: 'i1', name: 'Sulforaphane (NRF2 anti-inflammatory)', category: 'compound', evidence: 'A', rank: 1, impact: 9, description: 'Suppresses NF-κB via NRF2-ARE pathway. Reduces CRP in human airway studies.', compoundId: 'sulforaphane', pmid: '27356680', tnicAvailable: true },
      { id: 'i2', name: 'GlyNAC (glutathione / ROS)', category: 'compound', evidence: 'A', rank: 2, impact: 8, description: 'Reduces oxidative drivers of inflammation. Human trials show improved inflammatory markers.', compoundId: 'glynac', pmid: '36656670', tnicAvailable: true },
      { id: 'i3', name: 'Resveratrol (NF-κB / SIRT1)', category: 'compound', evidence: 'B', rank: 3, impact: 7, description: 'Modulates inflammatory gene expression via SIRT1 deacetylation of NF-κB subunits.', compoundId: 'resveratrol', tnicAvailable: true },
      { id: 'i4', name: 'Omega-3 (EPA+DHA)', category: 'compound', evidence: 'A', rank: 4, impact: 8, description: 'EPA/DHA generate resolvins, protectins, and maresins — specialized pro-resolving mediators that actively terminate inflammation. REDUCE-IT trial: 4g/day EPA reduced cardiovascular events 25% (PMID 30145934). Meta-analysis: significant hs-CRP and IL-6 reduction.', compoundId: 'omega3', pmid: '30145934', tnicAvailable: true },
      { id: 'i5', name: 'Zone 2 + resistance exercise', category: 'lifestyle', evidence: 'A', rank: 5, impact: 8, description: 'Myokines (IL-6 transient, IL-10 sustained) reprogram immune tone with training.', tnicAvailable: false },
    ],
  },
  {
    id: 'dysbiosis',
    slug: 'dysbiosis',
    number: 11,
    title: 'Dysbiosis',
    tagline: 'When the microbiome turns against you',
    summary: 'Age-related shifts in gut microbiota composition increase permeability ("leaky gut"), endotoxin translocation, and systemic inflammation.',
    mechanism: 'Reduced microbial diversity, loss of SCFA producers, and overgrowth of pro-inflammatory species drive the gut-inflammaging axis.',
    whyItMatters: 'The gut produces ~70% of systemic serotonin, trains immunity, and modulates NAD+ metabolism. Dysbiosis connects to nearly every hallmark.',
    visual: 'gut',
    coverage: 40,
    biomarkers: ['Zonulin', 'Calprotectin', 'Microbiome diversity index', 'SCFA levels'],
    relatedCompoundIds: ['sulforaphane'],
    mdxSlug: 'dysbiosis',
    personalPrompts: ['Log fiber intake daily', 'Track digestive symptoms', 'Note antibiotic courses'],
    interventions: [
      { id: 'd1', name: 'Diverse fiber / prebiotics', category: 'lifestyle', evidence: 'A', rank: 1, impact: 8, description: '30+ plant species per week feeds SCFA-producing taxa. Strongest evidence-based gut intervention.', tnicAvailable: false },
      { id: 'd2', name: 'Fermented foods daily', category: 'lifestyle', evidence: 'A', rank: 2, impact: 7, description: 'Stanford trial: 6 servings/day increased microbiome diversity and reduced inflammatory markers.', pmid: '34432955', tnicAvailable: false },
      { id: 'd3', name: 'Sulforaphane (gut NRF2)', category: 'compound', evidence: 'B', rank: 3, impact: 5, description: 'NRF2 activation in gut epithelium strengthens barrier function in preclinical models.', compoundId: 'sulforaphane', tnicAvailable: true },
      { id: 'd4', name: 'Targeted probiotics', category: 'compound', evidence: 'B', rank: 4, impact: 5, description: 'Akkermansia, Bifidobacterium longum strains show promise in pilot trials. Strain-specific.', tnicAvailable: false },
      { id: 'd5', name: 'Microbiome testing', category: 'clinical', evidence: 'B', rank: 5, impact: 4, description: 'Viome, Thorne, or clinical metagenomics to baseline and track intervention response.', tnicAvailable: false },
      { id: 'd6', name: 'Fermented foods (6 servings/day)', category: 'lifestyle', evidence: 'A', rank: 1, impact: 9, description: 'Stanford RCT (n=36, Cell 2021): fermented foods increased microbiome diversity 26% and reduced 19 inflammatory proteins including IL-6 and IL-12 — outperforming matched high-fiber diet for anti-inflammatory remodeling (PMID 34256014).', pmid: '34256014', tnicAvailable: false },
      { id: 'd7', name: 'Omega-3 (EPA/DHA gut barrier)', category: 'compound', evidence: 'B', rank: 4, impact: 6, description: 'EPA and DHA reduce intestinal permeability ("leaky gut"), shift microbiota toward anti-inflammatory species, and reduce LPS translocation-driven systemic inflammation. Strong mechanistic data; human gut-specific evidence emerging.', compoundId: 'omega3', tnicAvailable: true },
    ],
  },
  {
    id: 'nutrient',
    slug: 'disabled-macroautophagy',
    number: 12,
    title: 'Disabled Macroautophagy',
    tagline: 'Nutrient sensing gone wrong',
    summary: 'mTOR and AMPK — the nutrient sensing kinases — become dysregulated. Chronic nutrient surplus suppresses autophagy; AMPK activity declines with age.',
    mechanism: 'Insulin/IGF-1 activate mTOR (growth). Energy deficit activates AMPK (cleanup). Aging biases the balance toward mTOR dominance.',
    whyItMatters: 'Rapamycin (mTOR inhibitor) is the most replicated lifespan-extending drug in mice. Nutrient sensing is the master switch for repair vs growth.',
    visual: 'nutrient',
    coverage: 72,
    biomarkers: ['Fasting insulin', 'IGF-1', 'Ketone bodies', 'mTOR activity proxies'],
    relatedCompoundIds: ['resveratrol', 'nmn'],
    mdxSlug: 'disabled-macroautophagy',
    personalPrompts: ['Log daily eating window', 'Track fasting glucose', 'Note protein intake timing'],
    interventions: [
      { id: 'n1', name: 'Caloric moderation / fasting', category: 'lifestyle', evidence: 'A', rank: 1, impact: 9, description: 'Caloric restriction is the oldest lifespan intervention in mammals. mTOR suppression is the mechanism.', tnicAvailable: false },
      { id: 'n2', name: 'Resveratrol → AMPK', category: 'compound', evidence: 'B', rank: 2, impact: 7, description: 'Activates AMPK, mimicking energy deficit and promoting autophagy and mitochondrial biogenesis.', compoundId: 'resveratrol', tnicAvailable: true },
      { id: 'n3', name: 'NMN → SIRT1/mTOR balance', category: 'compound', evidence: 'B', rank: 3, impact: 7, description: 'Sirtuins counterbalance mTOR signaling; NAD+ decline removes this brake with age.', compoundId: 'nmn', tnicAvailable: true },
      { id: 'n4', name: 'Metformin (AMPK activator)', category: 'clinical', evidence: 'B', rank: 4, impact: 7, description: 'TAME trial — first FDA-approved trial targeting biological aging itself. Metformin activates AMPK via Complex I inhibition. Diabetics on metformin outlive age-matched non-diabetic controls — extraordinary longevity signal (PMID 32910831).', pmid: '32910831', tnicAvailable: false },
      { id: 'n6', name: 'Berberine (AMPK activator)', category: 'compound', evidence: 'A', rank: 6, impact: 7, description: 'Activates AMPK comparably to metformin. Head-to-head RCT: berberine 500mg TID reduced HbA1c 2.0% and fasting glucose 20% — equivalent to metformin (PMID 18396172). AMPK activation inhibits mTOR and restores autophagy signaling.', compoundId: 'berberine', pmid: '18396172', tnicAvailable: true },
      { id: 'n5', name: 'Rapamycin (mTOR inhibitor)', category: 'emerging', evidence: 'B', rank: 5, impact: 8, description: 'PEARL trial and dog aging studies. Prescription-only; immunosuppressive risks require physician oversight.', pmid: '19587683', tnicAvailable: false },
    ],
  },
];

export function getHallmarkBySlug(slug: string) {
  return hallmarkLibrary.find((h) => h.slug === slug);
}

export function getHallmarkById(id: string) {
  return hallmarkLibrary.find((h) => h.id === id);
}